#############################################################################
# Makefile for building: rocketbook
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  rocketbook.pro
# Template: subdirs
# Command: /usr/local/Qt/5.2.1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile rocketbook.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/local/Qt/5.2.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-model \
		sub-unittest-unittest \
		sub-database \
		sub-gui \
		sub-docs \
		sub-textui


sub-model-qmake_all:  FORCE
	@test -d model/ || mkdir -p model/
	cd model/ && $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile
	cd model/ && $(MAKE) -f Makefile qmake_all
sub-model: FORCE
	@test -d model/ || mkdir -p model/
	cd model/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile
sub-model-make_first: FORCE
	@test -d model/ || mkdir -p model/
	cd model/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-model-all: FORCE
	@test -d model/ || mkdir -p model/
	cd model/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-model-clean: FORCE
	@test -d model/ || mkdir -p model/
	cd model/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-model-distclean: FORCE
	@test -d model/ || mkdir -p model/
	cd model/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-model-install_subtargets: FORCE
	@test -d model/ || mkdir -p model/
	cd model/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-model-uninstall_subtargets: FORCE
	@test -d model/ || mkdir -p model/
	cd model/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-unittest-unittest-qmake_all:  FORCE
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile
	cd unittest/unittest/ && $(MAKE) -f Makefile qmake_all
sub-unittest-unittest: FORCE
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile
sub-unittest-unittest-make_first: FORCE
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-unittest-unittest-all: FORCE
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-unittest-unittest-clean: FORCE
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-unittest-unittest-distclean: FORCE
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-unittest-unittest-install_subtargets: FORCE
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-unittest-unittest-uninstall_subtargets: FORCE
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-database-qmake_all:  FORCE
	@test -d database/ || mkdir -p database/
	cd database/ && $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile
	cd database/ && $(MAKE) -f Makefile qmake_all
sub-database: FORCE
	@test -d database/ || mkdir -p database/
	cd database/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile
sub-database-make_first: FORCE
	@test -d database/ || mkdir -p database/
	cd database/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-database-all: FORCE
	@test -d database/ || mkdir -p database/
	cd database/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-database-clean: FORCE
	@test -d database/ || mkdir -p database/
	cd database/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-database-distclean: FORCE
	@test -d database/ || mkdir -p database/
	cd database/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-database-install_subtargets: FORCE
	@test -d database/ || mkdir -p database/
	cd database/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-database-uninstall_subtargets: FORCE
	@test -d database/ || mkdir -p database/
	cd database/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-gui-qmake_all:  FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile
	cd gui/ && $(MAKE) -f Makefile qmake_all
sub-gui: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile
sub-gui-make_first: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-gui-all: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-gui-clean: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-gui-distclean: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-gui-install_subtargets: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-gui-uninstall_subtargets: FORCE
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-docs-qmake_all:  FORCE
	@test -d docs/ || mkdir -p docs/
	cd docs/ && $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile
	cd docs/ && $(MAKE) -f Makefile qmake_all
sub-docs: FORCE
	@test -d docs/ || mkdir -p docs/
	cd docs/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile
sub-docs-make_first: FORCE
	@test -d docs/ || mkdir -p docs/
	cd docs/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-docs-all: FORCE
	@test -d docs/ || mkdir -p docs/
	cd docs/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-docs-clean: FORCE
	@test -d docs/ || mkdir -p docs/
	cd docs/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-docs-distclean: FORCE
	@test -d docs/ || mkdir -p docs/
	cd docs/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-docs-install_subtargets: FORCE
	@test -d docs/ || mkdir -p docs/
	cd docs/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-docs-uninstall_subtargets: FORCE
	@test -d docs/ || mkdir -p docs/
	cd docs/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-textui-qmake_all:  FORCE
	@test -d textui/ || mkdir -p textui/
	cd textui/ && $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile
	cd textui/ && $(MAKE) -f Makefile qmake_all
sub-textui: FORCE
	@test -d textui/ || mkdir -p textui/
	cd textui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile
sub-textui-make_first: FORCE
	@test -d textui/ || mkdir -p textui/
	cd textui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-textui-all: FORCE
	@test -d textui/ || mkdir -p textui/
	cd textui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-textui-clean: FORCE
	@test -d textui/ || mkdir -p textui/
	cd textui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-textui-distclean: FORCE
	@test -d textui/ || mkdir -p textui/
	cd textui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-textui-install_subtargets: FORCE
	@test -d textui/ || mkdir -p textui/
	cd textui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-textui-uninstall_subtargets: FORCE
	@test -d textui/ || mkdir -p textui/
	cd textui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: rocketbook.pro /usr/local/Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf /usr/local/Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/unix.conf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/linux.conf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/qconfig.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/lex.prf \
		rocketbook.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile rocketbook.pro
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/unix.conf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/linux.conf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/qconfig.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf:
/usr/local/Qt/5.2.1/gcc_64/mkspecs/features/lex.prf:
rocketbook.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile rocketbook.pro

qmake_all: sub-model-qmake_all sub-unittest-unittest-qmake_all sub-database-qmake_all sub-gui-qmake_all sub-docs-qmake_all sub-textui-qmake_all FORCE

make_first: sub-model-make_first sub-unittest-unittest-make_first sub-database-make_first sub-gui-make_first sub-docs-make_first sub-textui-make_first FORCE
all: sub-model-all sub-unittest-unittest-all sub-database-all sub-gui-all sub-docs-all sub-textui-all FORCE
clean: sub-model-clean sub-unittest-unittest-clean sub-database-clean sub-gui-clean sub-docs-clean sub-textui-clean FORCE
distclean: sub-model-distclean sub-unittest-unittest-distclean sub-database-distclean sub-gui-distclean sub-docs-distclean sub-textui-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-model-install_subtargets sub-unittest-unittest-install_subtargets sub-database-install_subtargets sub-gui-install_subtargets sub-docs-install_subtargets sub-textui-install_subtargets FORCE
uninstall_subtargets: sub-model-uninstall_subtargets sub-unittest-unittest-uninstall_subtargets sub-database-uninstall_subtargets sub-gui-uninstall_subtargets sub-docs-uninstall_subtargets sub-textui-uninstall_subtargets FORCE

sub-model-check:
	@test -d model/ || mkdir -p model/
	cd model/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/model/model.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-unittest-unittest-check:
	@test -d unittest/unittest/ || mkdir -p unittest/unittest/
	cd unittest/unittest/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/unittest/unittest/unittest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-database-check:
	@test -d database/ || mkdir -p database/
	cd database/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/database/database.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-gui-check:
	@test -d gui/ || mkdir -p gui/
	cd gui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/gui/gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-docs-check:
	@test -d docs/ || mkdir -p docs/
	cd docs/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/docs/docs.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-textui-check:
	@test -d textui/ || mkdir -p textui/
	cd textui/ && ( test -e Makefile || $(QMAKE) /auto/bunter_usr23/townleym/wc20160420/textui/textui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=declarative_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-model-check sub-unittest-unittest-check sub-database-check sub-gui-check sub-docs-check sub-textui-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

